name: website
description: A new shelf project.
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^3.0.0
  dotenv: ^4.2.0
  web_socket_channel: ^3.0.3
  uuid: ^4.5.1
  sqlite3: ^2.7.5
  shelf_static: ^1.1.3
  markdown: ^7.3.0
  mime: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.1.4
